### ISSUE TITLE
unrecognized structureElement StringLiteral

### ISSUE THREAD

**Issue by Hareem-E-Sahar** [SAG-KeLP/kelp-full#19]
Has anyone faced this issue and knows a workaround? Below is the exception I get while setting data using setDataFromText() function.

`[main] WARN it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel - Increasing the size of cache matrices to host trees with height=22 and maxBranchingFactor=50
[main] WARN it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel - Increasing the size of cache matrices to host trees with height=34 and maxBranchingFactor=391
[main] WARN it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel - Increasing the size of cache matrices to host trees with height=22 and maxBranchingFactor=50
[main] WARN it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel - Increasing the size of cache matrices to host trees with height=23 and maxBranchingFactor=153
[main] WARN it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel - Increasing the size of cache matrices to host trees with height=30 and maxBranchingFactor=50
[main] WARN it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel - Increasing the size of cache matrices to host trees with height=24 and maxBranchingFactor=50
java.lang.IllegalArgumentException: unrecognized structureElement StringLiteral:"
	at it.uniroma2.sag.kelp.data.representation.structure.StructureElementFactory.parseStructureElement(StructureElementFactory.java:121)
	at it.uniroma2.sag.kelp.data.representation.structure.StructureElementFactory.parseStructureElement(StructureElementFactory.java:154)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO.parseNode(TreeIO.java:141)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:89)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO._parseCharniakSentence(TreeIO.java:124)
	at it.uniroma2.sag.kelp.data.representation.tree.utils.TreeIO.parseCharniakSentence(TreeIO.java:56)
	at it.uniroma2.sag.kelp.data.representation.tree.TreeRepresentation.setDataFromText(TreeRepresentation.java:253)`
	
Any help is appreciated.

**Comment by Hareem-E-Sahar** [comment]
caused by StringLiteral:"{0,number,#.###}"
Removing # would resolve the issue. But its tedious to remove this from my data.

**Comment by SimoneFilice** [comment]
Hi,

A single '#' is allowed but two or more are not.
Unfortunately, we used '##' as a special sequence (https://github.com/SAG-KeLP/kelp-additional-kernels/blob/development/src/main/java/it/uniroma2/sag/kelp/data/representation/structure/StructureElementFactory.java#L41).

Best,
Simone
