### ISSUE TITLE
Error running PTK with large trees

### ISSUE THREAD

**Issue by sromeo** [SAG-KeLP/kelp-full#5]
Hi, 

I am trying to use the PTK with large trees and I receive the following error:

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 50
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:386)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.stringKernelDeltaFunction(PartialTreeKernel.java:405)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.ptkDeltaFunction(PartialTreeKernel.java:330)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.evaluateKernelNotNormalize(PartialTreeKernel.java:261)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.kernelComputation(PartialTreeKernel.java:302)
	at it.uniroma2.sag.kelp.kernel.tree.PartialTreeKernel.kernelComputation(PartialTreeKernel.java:1)
	at it.uniroma2.sag.kelp.kernel.DirectKernel.kernelComputation(DirectKernel.java:66)
	at it.uniroma2.sag.kelp.kernel.Kernel.squaredNorm(Kernel.java:170)
	at it.uniroma2.sag.kelp.kernel.standard.NormalizationKernel.kernelComputation(NormalizationKernel.java:49)
	at it.uniroma2.sag.kelp.kernel.Kernel.innerProduct(Kernel.java:93)
	at it.uniroma2.sag.kelp.kernel.pairs.UncrossedPairwiseProductKernel.kernelComputationOverPairs(UncrossedPairwiseProductKernel.java:94)
	at it.uniroma2.sag.kelp.kernel.pairs.KernelOnPairs.kernelComputation(KernelOnPairs.java:42)
	at it.uniroma2.sag.kelp.kernel.Kernel.innerProduct(Kernel.java:93)
	at it.uniroma2.sag.kelp.kernel.standard.LinearKernelCombination.kernelComputation(LinearKernelCombination.java:94)
	at it.uniroma2.sag.kelp.kernel.Kernel.innerProduct(Kernel.java:89)
	at KernelCacheCreatorTaskD.main(KernelCacheCreatorTaskD.java:79)
`

Thanks in advance
Salvatore

**Comment by crux82** [comment]
Hi Salvatore, 

It is actually a bug in the PTK implementation. I should have resolved it.
These changes have been committed into the 2.2.1-SNAPSHOT version of Kelp (that you should include in your project). 

Can you confirm that your issue has been solved?

Best regards

Danilo

**Comment by sromeo** [comment]
Hi Danilo,

I confirm, the issue is solved.

Best regards
Salvatore

**Comment by aszx4510** [comment]
Hi Danilo,
I found a similar problem while I was using SPTK.

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 20
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:382)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.smoothedStringKernelDeltaFunction(SmoothedPartialTreeKernel.java:399)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.sptkDeltaFunction(SmoothedPartialTreeKernel.java:464)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.evaluateKernelNotNormalize(SmoothedPartialTreeKernel.java:253)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.kernelComputation(SmoothedPartialTreeKernel.java:307)
	at it.uniroma2.sag.kelp.kernel.tree.SmoothedPartialTreeKernel.kernelComputation(SmoothedPartialTreeKernel.java:79)
	at it.uniroma2.sag.kelp.kernel.DirectKernel.kernelComputation(DirectKernel.java:66)
	at it.uniroma2.sag.kelp.kernel.Kernel.innerProduct(Kernel.java:89)
	at it.uniroma2.sag.kelp.learningalgorithm.classification.libsvm.solver.LibSvmSolver.kernel(LibSvmSolver.java:365)
	at it.uniroma2.sag.kelp.learningalgorithm.classification.libsvm.solver.LibSvmSolver.get_QD(LibSvmSolver.java:264)
	at it.uniroma2.sag.kelp.learningalgorithm.classification.libsvm.solver.LibSvmSolver.solve(LibSvmSolver.java:524)
	at it.uniroma2.sag.kelp.learningalgorithm.classification.libsvm.BinaryCSvmClassification.learn(BinaryCSvmClassification.java:187)
	at it.uniroma2.sag.kelp.learningalgorithm.classification.libsvm.BinaryCSvmClassification.learn(BinaryCSvmClassification.java:164)
	at tw.edu.sinica.iis.iasl.PoliticalTreeExperiment.Test.main(Test.java:65)
```

2.2.1-SNAPSHOT also solved this problem?
I can't update to 2.2.1-SNAPSHOT automatically by Maven.
How can I change version to 2.2.1?

Best regards
Wind

**Comment by crux82** [comment]
Dear Wind, 

the version 2.2.1-SNAPSHOT solved this issue, so you should import this last version.

How did you import Kelp? Did you use Maven? Or did you add the Jar Files?
If you imported KeLP via Maven, you should change the POM file of your project. (I will support you in this procedure).

Best regards

Danilo

**Comment by aszx4510** [comment]
Dear Danilo,

Yes, I import KeLP via Maven, 
Last week, I modified version 2.1.0 to 2.2.0 successfully.
Now,  I can't change version to 2.2.1 .
I have no idea. D:

```
<dependency>
      <groupId>it.uniroma2.sag.kelp</groupId>
      <artifactId>kelp-full</artifactId>
      <version>2.2.0</version>
    </dependency>
  </dependencies>
```




This is my pom.xml 

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>tw.edu.sinica.iis.iasl</groupId>
  <artifactId>HotelReviewSentiment</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>HotelReviewSentiment</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  
  <repositories>
    <repository>
      <id>kelp_repo_snap</id>
      <name>KeLP Snapshots Repository</name>
      <releases>
        <enabled>false</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>warn</checksumPolicy>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>fail</checksumPolicy>
      </snapshots>
      <url>http://sag.art.uniroma2.it:8081/artifactory/kelp-snapshot/</url>
    </repository>
    <repository>
      <id>kelp_repo_release</id>
        <name>KeLP Stable Repository</name>
        <releases>
          <enabled>true</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>warn</checksumPolicy>
        </releases>
        <snapshots>
          <enabled>false</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </snapshots>
      <url>http://sag.art.uniroma2.it:8081/artifactory/kelp-release/</url>
    </repository>
  </repositories>	

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>it.uniroma2.sag.kelp</groupId>
      <artifactId>kelp-full</artifactId>
      <version>2.2.0</version>
    </dependency>
  </dependencies>
</project>
```

Best regards
Wind

**Comment by SimoneFilice** [comment]
Hi Wind,

In the final part on your POM file try to change row:

\<version>2.2.0\</version>

into

\<version>2.2.1-SNAPSHOT\</version>

Please, let us know whether it worked.

Best,
Simone

**Comment by aszx4510** [comment]
Hi Simone, 

Already update to 2.2.1-SNAPSHOT successfully.
"SNAPSHOT" is part of version name, I never think about that. :P
Finally, the bug has been solved.

Thank you!
Wind
